---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: synator
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: synator
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["*"]
- apiGroups: [events.k8s.io]
  resources: [events]
  verbs: [create]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
- apiGroups: [""]
  resources: ["namespaces", "pods", "replicasets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: synator
subjects:
- kind: ServiceAccount
  name: synator
  namespace: default
roleRef:
  kind: ClusterRole
  name: synator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: synator
  template:
    metadata:
      labels:
        name: synator
    spec:
      serviceAccountName: synator
      containers:
        - name: synator
          image: theykk/synator:v0.10
